### ISSUE TITLE
Link to GitHub team makes governance appear opaque to non-members

### ISSUE THREAD

**Issue by joshuagl** [ossf/wg-securing-software-repos#15]
The [Governance](https://github.com/ossf/wg-securing-software-repos#governance) section of the README links to the GitHub team, but GitHub teams are not visible to readers who are not members of the teams' organisation. The link in the README is a 404 for me.

Teams have two states, [visible and secret](https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams#team-visibility). Visible teams can be viewed and mentioned **by organisation members**. Secret teams can be viewed and mentioned only by people on the team and organisation owners.

**Comment by znewman01** [comment]
Thanks for pointing that out, certainly not the intention :) 

CC @di who may be able to fix this

**Comment by joshuagl** [comment]
Thanks! I realised I can see 9 of the 44 teams in https://github.com/orgs/ossf/teams --- which implies there's a third visibility state for teams?

**Comment by di** [comment]
This team seems to just not exist anymore. I also seem to have lost the ability to administer this repo or change the collaborators. @hythloda, was this intentional? 

Regardless of that, do we need this line in the readme? If so, what should it link to, the maintainers of this repo?

**Comment by ljharb** [comment]
@di you should have Maintain privileges on the repo, is that not sufficient?

**Comment by di** [comment]
@ljharb It doesn't give me the ability to add/remove collaborators to these teams, modify settings on this repository, etc. Not sure if that was intentional or not but IMO the chair(s) of a given WG should probably have those abilities at least.

**Comment by ljharb** [comment]
That makes sense to me; now yourself and Bob are "maintainers" of the base team (which grants Maintain access). There's a separate team that grants Admin access, that only Bob is on atm. Please let me or @hythloda know if you need any adjustments to the team structure.

**Comment by ljharb** [comment]
The latter.

**Comment by simi** [comment]
Is the list at CHARTER.md?

https://github.com/ossf/wg-securing-software-repos/blob/66d897be3d7ab9bdb72a76afe35c9825c8632ef1/CHARTER.md#8-maintainers

**Comment by hythloda** [comment]
There are two different things people have been doing, the CHARTER.md file listing collaborators like above and a [MEMBERS.md file](https://github.com/ossf/wg-best-practices-os-developers/blob/main/members.md).  

What we have been trying to do is:
contributors = write
maintainers = maintain
leads = admin

Leads are on all the lists as maintainers and can add and remove people to the lists as they need/want.  I *think* this is working well. 

Does this seems like a solution that has been working? Willing to iterate on something else if this isn't functioning well. otherwise, let's close this up as solved!
